version: "3.9"
services:
  filesgo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/cloud.db:/app/cloud.db
    environment:
      - GIN_MODE=release
